spring:
  application:
    name: api-gateway

  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      routes:
        - id: api-auth
          uri: lb://api-auth
          predicates:
            - Path=/auth/**

        - id: api-account
          uri: lb://api-account
          predicates:
            - Path=/accounts/**

        - id: insper
          uri: https://www.insper.edu.br
          predicates:
            - Path=/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

api:
  endpoints:
    open: >
        ANY /auth/register,
        POST /auth/login
