spring:
  application:
    name: gateway

  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      routes:
        - id: api-auth
          uri: lb://api-auth
          predicates:
            - Path=/auth/**

        - id: api-account
          uri: lb://api-account
          predicates:
            - Path=/accounts/**

        - id: api-ingredientes
          uri: lb://api-ingredientes
          predicates:
            - Path=/ingredientes/**

        - id: api-receitas
          uri: lb://api-receitas
          predicates:
            - Path=/receitas/**
management:
  endpoints:
    web:
      base-path: /gateway/actuator
      exposure:
        include: [ 'prometheus' ]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://${DISCOVERY_HOST}:8761/eureka/}

api:
  endpoints:
    open: >
      POST /auth/register,
      POST /auth/login,
      ANY /auth/actuator,
      ANY /accounts/actuator,
      ANY /receitas/actuator,
      ANY /ingredientes/actuator,
      ANY /ingredientes/**,
      ANY /receitas/**

